-- AULA 21

-- SUB-CONSULTAS - SUB-SELECT
SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
WHERE TOTAL > -- TOTAL MAIOR QUE VALOR DO CURSO DE COD. 1
  (
    SELECT VALOR FROM TCURSO
    WHERE COD_CURSO = 1
  );

-- ERRADO (SÓ PODE RETORNAR 1 LINHA NA SUBCONSULTA)
SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
WHERE TOTAL >= (
  -- SELECT DE COLUNAS DE ACORDO COM SELECT DO WHERE
  --  SE WHERE CONTER APENAS UMA COLUNA, REALIZAR SUBSELECT COM APENAS UMA COL.
  SELECT VALOR FROM TCURSO
    WHERE VALOR > 500  -- VAI RETORNAR MAIS DE 1 REGISTRO
);

SELECT * FROM TALUNO

UPDATE TALUNO SET
  ESTADO = 'SP'
WHERE COD_ALUNO = 1
OR COD_ALUNO = 2



-- TODOS OS ALUNOS DA MESMA CIDADE DO ALUNO 1, MENOS O ALUNO 1
SELECT COD_ALUNO, NOME, CIDADE
FROM TALUNO
WHERE CIDADE = (
  SELECT CIDADE FROM TALUNO
    WHERE COD_ALUNO = 1
)
AND COD_ALUNO <> 1;

-- TODOS OS ALUNOS DA MESMA CIDADE E ESTADO DO ALUNO 1, MENOS O ALUNO 1
SELECT COD_ALUNO, NOME, CIDADE
FROM TALUNO
-- ENTRE PARÊNTESES QUANDO WHERE COM MAIS DE UMA COLUNA
WHERE (CIDADE, ESTADO) = (
  SELECT CIDADE, ESTADO FROM TALUNO
    WHERE COD_ALUNO = 1
)
AND COD_ALUNO <> 1;


-- SOMA TODOS OS ITENS E RETORNA SOMENTE CUJO VALOR SEJA MAIOR
--  QUE O VALOR MÉDIO DOS CURSOS
SELECT COD_CURSO, Min(VALOR), Sum(VALOR),
       Count(*) QTDE
FROM TITEM
WHERE COD_CURSO > 0
GROUP BY COD_CURSO
HAVING Min(VALOR) >= (
  SELECT Avg(VALOR) FROM TCURSO
)
ORDER BY COD_CURSO;


COMMIT;


-- SOMA O TOTAL DE CONTRATO POR ALUNO E RETORNA SOMENTE CUJO O MENOR CONTRATO
--  SEJA MAIOR QUE O VALOR MÉDIO DE CURSO
SELECT COD_ALUNO, Min(TOTAL), Sum(TOTAL)
FROM TCONTRATO
GROUP BY COD_ALUNO
HAVING Min(TOTAL) > (
  SELECT Avg(VALOR) FROM TCURSO
);


-- TODOS OS CURSOS QUE ESTÃO NA TABELA DE ITEM (VENDIDOS)
SELECT COD_CURSO, NOME, VALOR
FROM TCURSO
-- NESSE CASO, RETORNA MAIS DE UM REGISTRO (AO UTILIZAR O IN)
WHERE COD_CURSO IN (SELECT COD_CURSO FROM TITEM)

-- TODOS OS CURSOS QUE NÃO ESTÃO NA TABELA DE ITEM (NÃO FORAM VENDIDOS)
SELECT COD_CURSO, NOME, VALOR
FROM TCURSO
WHERE COD_CURSO NOT IN (SELECT COD_CURSO FROM TITEM)
ORDER BY NOME ASC

-- CÓDIGO CORRESPONDENTE AO SUBSELECT
--  (SE VALORES FOREM CONHECIDOS)
SELECT COD_CURSO, NOME, VALOR
FROM TCURSO WHERE COD_CURSO IN(1, 2, 3, 4)

-- CÓDIGO CORRESPONDENTE AO SUBSELECT
--  (SE VALORES FOREM CONHECIDOS)
SELECT COD_CURSO, NOME, VALOR
FROM TCURSO
WHERE COD_CURSO = 1
OR COD_CURSO = 2
OR COD_CURSO = 3
OR COD_CURSO = 4


-- TODOS CURSOS QUE FORAM VENDIDOS PELO VALOR PADRÃO
SELECT * FROM TITEM
WHERE (COD_CURSO, VALOR) IN
      (SELECT COD_CURSO, VALOR FROM TCURSO)


-- SUBCONSULTA NA CLÁUSULA FROM
SELECT ITE.COD_CONTRATO,
       ITE.VALOR,
       ITE.COD_CURSO "CODIGO DO CURSO VENDIDO",
       CUR.COD_CURSO "CODIGO DO CURSO",
       CUR.VALOR
FROM TITEM ITE,
     (
       SELECT COD_CURSO, VALOR
       FROM TCURSO WHERE VALOR > 500
     ) CUR
WHERE CUR.COD_CURSO = ITE.COD_CURSO


COMMIT;
























