-- AULA 19
-- FUNÇÕES DE GRUPO

SELECT * FROM TCONTRATO;

SELECT Count(*) AS QTDE_REGISTROS, -- CONTAR TODOS REGISTROS
       Avg(TOTAL) AS MEDIA,
       Round(Avg(TOTAL), 2) AS MEDIA, -- ARREDONDAR A MEDIA EM DUAS CASAS
       Max(TOTAL) AS MAXIMO, -- VALOR MÁXIMO
       Min(TOTAL) AS MINIMO, -- VALOR MÍNIMO
       Sum(TOTAL) AS SOMA,
       Max(DATA)  AS DATA_MAIOR,
       Min(DATA)  AS DATA_MENOR
FROM TCONTRATO;


-- PROXIMO CÓDIGO SEQUENCIAL TABELA
SELECT Max(COD_CONTRATO) AS PROXIMO_CODIGO
FROM TCONTRATO;


SELECT * FROM TCONTRATO;
SELECT * FROM TALUNO;


SELECT COD_ALUNO,
       Count(*) AS QTDE_CONTRATO,
       Sum(TOTAL) AS VALOR_TOTAL
FROM TCONTRATO
-- SEMPRE QUE UTILIZAR FUNÇÃO DE AGRUPAMENTO,
-- PRECISA AGRUPAR SEMPRE POR COLUNA SEM FUNÇÃO DE GRUPO
GROUP BY COD_ALUNO


SELECT To_Char(Trunc(SYSDATE), 'DD/MM/YYYY') AS DAT FROM DUAL

SELECT To_Char(Trunc(DATA), 'DD/MM/YYYY') AS DATA,
       Sum(TOTAL) AS SOMA,
       Round(Avg(TOTAL), 2) AS MEDIA,
       Count(*)   AS QTDE
FROM TCONTRATO
GROUP BY Trunc(DATA)
ORDER BY DATA DESC

COMMIT;


-- AULA 20

SELECT * FROM TCONTRATO

UPDATE TCONTRATO SET
  DESCONTO = NULL
WHERE COD_CONTRATO = 4;

UPDATE TCONTRATO SET
  DESCONTO = NULL
WHERE COD_CONTRATO = 3;

SELECT Count(*) QTDE_REGISTROS
FROM TCONTRATO;

-- COUNT -> IGNORA NULOS
SELECT Count(DESCONTO)
FROM TCONTRATO;

SELECT * FROM TALUNO

UPDATE TALUNO SET
  ESTADO = 'MT'
WHERE COD_ALUNO = 6

-- QTDE DE REGISTROS COM ESTADO INFORMADO
SELECT Count(ESTADO) FROM TALUNO;

-- QTDE DE ESTADOS DIFERENTES (DISTINCT)
SELECT Count(DISTINCT(ESTADO)) FROM TALUNO

-- QTDE DE REGISTROS POR ESTADO
SELECT ESTADO, Count(*)
FROM TALUNO
GROUP BY ESTADO;

SELECT Sum(DESCONTO),
       Avg(DESCONTO),
       Count(DESCONTO),
       Round(Avg(Nvl(DESCONTO, 0)), 2)
FROM TCONTRATO;

COMMIT;


SELECT * FROM TCONTRATO

-- TOTAL DE CONTRATO POR ESTADO E DATA
SELECT ALU.ESTADO, Trunc(CON.DATA) AS DATA,
       Sum(CON.TOTAL) TOTAL, Count(*) QTDE
FROM TALUNO ALU, TCONTRATO CON
WHERE ALU.COD_ALUNO = CON.COD_ALUNO
GROUP BY ALU.ESTADO, Trunc(CON.DATA)
ORDER BY ALU.ESTADO, DATA DESC;

-- TOTAL DE CONTRATO POR ESTADO
SELECT ALU.ESTADO,
       Sum(CON.TOTAL) TOTAL,
       Count(*) QTDE
FROM TALUNO ALU, TCONTRATO CON
WHERE ALU.COD_ALUNO = CON.COD_ALUNO
GROUP BY ALU.ESTADO
ORDER BY ALU.ESTADO;


-- HAVING -> FILTRAR COLUNA COM FUNÇÃO DE GRUPO
SELECT COD_ALUNO, Avg(TOTAL) MEDIA
FROM TCONTRATO
WHERE COD_ALUNO > 0 -- SEM EFEITO E NÃO NECESSÁRIO
HAVING Avg(TOTAL) > 500 -- HAVENDO/TENDO
GROUP BY COD_ALUNO
ORDER BY COD_ALUNO

SELECT Trunc(DATA) DATA, Sum(TOTAL) TOTAL
FROM TCONTRATO
WHERE COD_CONTRATO > 0
GROUP BY Trunc(DATA)
HAVING Sum(TOTAL) > 500
ORDER BY TOTAL DESC;


-- MEDIA MAIS ALTA DE ALUNO
SELECT Max(Avg(TOTAL))
FROM TCONTRATO
GROUP BY COD_ALUNO;

-- SOMA DOS SALARIOS POR ESTADO
SELECT ESTADO, Sum(SALARIO) AS TOTAL
FROM TALUNO
GROUP BY ESTADO
ORDER BY TOTAL DESC


COMMIT;
































