/*
  AULA 10

  FUNÇÕES DO TIPO SINGLE-ROW
  - MANIPULAM ITENS DE DADOS
  - RECEBEM ARGUMENTOS E RETORNAM UM VALOR
  - ATUAM SOBRE CADA LINHA RECUPERADA
  - RETORNAM UM RESULTADO POR LINHA
  - PODEM MODIFICAR O TIPO DE UM DADO
  - PODEM SER ANINHADAS

  FUNCTION_NAME (COLUMN|EXPRESSION, [ARG1, ARG2, ...])

  AS MULTIPLE-ROW FUNCTIONS NO ORACLE SÃO USADAS PARA RETORNAR
    UM GRUPO DE VALORES (OU) UM ÚNICO VALOR
*/

SELECT * FROM TALUNO

-- JUNTA VALORES DE COLUNAS
SELECT CONCAT(COD_ALUNO, NOME) FROM TALUNO;

-- MESMO EFEITO
SELECT COD_ALUNO||NOME FROM TALUNO;

SELECT COD_ALUNO||' '||NOME FROM TALUNO;

-- TRANSFORMA A PRIMEIRA LETRA EM MAIÚSCULA DE CADA PALAVRA
SELECT NOME, INITCAP(NOME) FROM TALUNO;

SELECT INITCAP('MATEUS DA SILVA') FROM TALUNO;

-- RETORNAR APENAS UMA VEZ
SELECT INITCAP('MATEUS DA SILVA') FROM DUAL;

-- VERIFICAR EM QUAL POSIÇÃO A LETRA APARECEU NA PALAVRA
SELECT NOME, INSTR(NOME, 'R') FROM TALUNO;

-- CONTA QUANTOS CARACTERES TÊM
SELECT NOME, LENGTH(NOME) FROM TALUNO

-- TRANSFORMA OS VALORES EM MINÚSCULO
SELECT NOME, LOWER(NOME) FROM TALUNO;

-- TRANSFORMA OS VALORES EM MAIÚSCULO
SELECT NOME, UPPER(NOME) FROM TALUNO;

-- L = LEFT - ESQUERDA, PREENCHE COM O 'VALOR'
--  NA QUANTIDADE À ESQUERDA, ATÉ O VALOR PREENCHER AS CASAS
SELECT COD_ALUNO, LPAD(COD_ALUNO, 5, '0') FROM TALUNO;

-- MESMO EFEITO À DIREITA
SELECT NOME, RPAD(SALARIO, 8, '0') AS SALARIO FROM TALUNO ;

SELECT NOME, RPAD(NOME, 10, '@') FROM TALUNO;

-- COPIA PARTE DE UM TEXTO (VALOR, POSIÇÃO INICIAL, QTD. CARACTR)
SELECT NOME, SUBSTR(NOME, 1, 3) FROM TALUNO;

SELECT NOME, SUBSTR(NOME, 1, 1) FROM TALUNO;

SELECT NOME, SUBSTR(NOME, 3, 2) FROM TALUNO;

-- SUBSTITUIR TODOS 'R' POR '$' DO CAMPO
SELECT REPLACE(NOME, 'R', '$') FROM TALUNO;

-- FUNÇÕES ANINHADAS
SELECT REPLACE(UPPER(NOME), 'R', '$') FROM TALUNO;

-- RETORNAR A ÚLTIMA LETRA
SELECT NOME, SUBSTR(NOME, LENGTH(NOME), 1) FROM TALUNO;

-- RETORNA OS DOIS ÚLTIMOS
SELECT NOME, SUBSTR(NOME, LENGTH(NOME)-1, 2) FROM TALUNO;

-- COPIA A PARTIR DA POSIÇÃO 3 OS 3 PRÓXIMOS CARACTERES
SELECT NOME, SUBSTR(NOME, 3, LENGTH(NOME)-3) FROM TALUNO;


-- AULA 11

-- TRANSFORMA EM MINÚSCULO
SELECT * FROM TALUNO
WHERE LOWER(NOME) = 'RENAN';

-- TRANSFORMA EM MAIÚSCULO
SELECT * FROM TALUNO
WHERE UPPER(NOME) = 'RENAN';

-- COPIA AS 3 PRIMEIRAS LETRAS E TRANSFORMAR EM MAIÚSCULO
--  E COMPARAR COM A STRING
SELECT * FROM TALUNO
WHERE UPPER(SUBSTR(CIDADE, 1, 3)) = 'ITA'

UPDATE TALUNO SET
SALARIO = 833.47
WHERE COD_ALUNO = 1;

SELECT
  SALARIO,
  REPLACE(SALARIO, '.' , ' '),
  RPAD(SALARIO, 10, '0'), -- ZEROS À DIREITA ATÉ 10 CASAS
  LPAD(SALARIO, 10, '0'), -- ZEROS À ESQUERDA ATÉ 10 CASAS
  LPAD(REPLACE(SALARIO, '.', ' '), 10, '0')
FROM TALUNO;

-- ROUND E TRUNC
SELECT ROUND(45.925, 2), -- 45.93, ARREDONDAR EM DUAS CASAS
       TRUNC(45.929, 2), -- 45.92, TRUNCA (ARREDONDA PARA BAIXO) EM DUAS CASAS
       MOD(10, 2) AS RESTO_DIVISAO, -- DIVIDE 10 POR 2 E RETORNA O RESTO
       TRUNC(1.99),
       TRUNC(1.99, 2)
FROM DUAL;


-- AULA 12: DATA

SELECT * FROM DUAL;

-- SYSDATE RETORNA DATA/HORA DO SERVIDOR
SELECT SYSDATE FROM DUAL;


-- FUNÇÕES DE DATA/HORA

-- SOMAR + 5 DIAS
SELECT DATA, SYSDATE, DATA + 5 FROM TCONTRATO;

-- DATA DE HOJE - VALOR DA DATA
SELECT SYSDATE - DATA AS DIFERENCA_DIAS FROM TCONTRATO;

-- PARA NÃO RETORNAR A HORA (VALOR MUITO GRANDE)
SELECT TRUNC(SYSDATE - DATA) AS DIFERENCA_DIAS FROM TCONTRATO;

-- SOMAR HORAS EM UMA DATA
-- DATA ATUAL + 2 HORAS (DIVIDIDO POR 24 HORAS = 1 DIA)
SELECT SYSDATE, SYSDATE + 2 / 24 AS ADD_HORAS FROM TCONTRATO;

-- SOMAR MINUTOS EM UMA DATA
-- DATA ATUAL + 15 MINUTOS (DIVIDIDO PELOS MINUTOS EM 1 DIA = 1440)
SELECT SYSDATE, SYSDATE + 15 / 1440 AS ADD_MINUTOS FROM TCONTRATO;

-- SOMAR SEGUNDOS EM UMA DATA
-- DATA ATUAL + 30 SEGUNDOS (DIVIDIDO PELOS SEGUNDOS EM 1 HORA = 3600
--  MULTIPLICADO POR 24 HORAS)
SELECT SYSDATE, SYSDATE + 30 / (3600 * 24) AS ADD_SEGUNDOS FROM TCONTRATO


-- HORA FICA 00:00:00
SELECT SYSDATE, TRUNC(SYSDATE) FROM DUAL;

-- DIFERENÇA DE MESES ENTRE DATAS
SELECT MONTHS_BETWEEN(SYSDATE, SYSDATE-90) AS DIF_MES FROM DUAL;

-- ADICIONA MESES
SELECT SYSDATE, ADD_MONTHS(SYSDATE, 5) AS ADD_MES_DATA FROM DUAL;

-- PROXIMA DATA A PARTIR DE UM DIA DA SEMANA
SELECT NEXT_DAY(SYSDATE, 'QUARTA-FEIRA') AS PROXIMA_QUARTA_DATA FROM DUAL;
SELECT NEXT_DAY(SYSDATE, 'WEDNESDAY') AS PROXIMA_QUARTA_DATA FROM DUAL;

-- ÚLTIMO DIA DO MÊS
SELECT LAST_DAY(SYSDATE) AS ULTIMO_DIA_MES FROM DUAL;

-- PRIMEIRO DIA DO PRÓXIMO MÊS
-- ATÉ DIA 15 DO MÊS: RETORNA O PRIMEIRO DIA DO MÊS ATUAL
--  A PARTIR DO DIA 16: RETORNA O PRIMEIRO DIA DO PRÓXIMO MÊS
SELECT ROUND(SYSDATE, 'MONTH') AS PRIMEIRO_DIA_PROXIMO_MES FROM DUAL;

-- PRIMEIRO DIA DO MÊS CORRENTE
SELECT TRUNC(SYSDATE, 'MONTH') AS PRIMEIRO_DIA_MES_CORRENTE FROM DUAL;


-- AULA 13: FORMATAÇÃO DE DATA

-- CONVERSOR TO_CHAR(DATA, FORMATO)
--  CONVERTE PARA STRING

-- FORMATAR A DATA EM DIA -> DD
SELECT SYSDATE, TO_CHAR(SYSDATE, 'DD') DIA FROM DUAL;

-- FORMATAR A DATA EM MÊS -> MM
SELECT SYSDATE, TO_CHAR(SYSDATE, 'MM') MES FROM DUAL;

-- FORMATAR A DATA EM ANO -> YYYY
SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY') ANO FROM DUAL;

-- FORMATAR A DATA EM ANO -> YY
SELECT SYSDATE, TO_CHAR(SYSDATE, 'YY') ANO FROM DUAL;

-- FORMATAR A DATA EM DIA/MÊS/ANO -> DD/MM/YYYY
SELECT SYSDATE, TO_CHAR(SYSDATE, 'DD/MM/YYYY') DATA FROM DUAL;

-- FORMATAR A DATA EM DIA/MÊS -> DD/MM
SELECT SYSDATE, TO_CHAR(SYSDATE, 'DD/MM') DIA_MES FROM DUAL;

-- RETORNAR MÊS ATUAL
SELECT TO_CHAR(SYSDATE, 'MONTH') MES FROM DUAL;

-- RETORNAR NÚMERO DO DIA DA SEMANA
SELECT TO_CHAR(SYSDATE, 'D') DIA_SEMANA FROM DUAL;

-- RETORNAR NÚMERO DO DIA DA SEMANA
SELECT TO_CHAR(SYSDATE, 'DY') DIA_SEMANA FROM DUAL;  -- QUA -> WED

-- RETORNAR NÚMERO DO DIA DA SEMANA
SELECT TO_CHAR(SYSDATE, 'DAY') DIA_SEMANA FROM DUAL;  -- QUARTA -> WEDNESDAY

-- RETORNAR NÚMERO DO DIA DA SEMANA
SELECT TO_CHAR(SYSDATE, 'YEAR') DIA_SEMANA FROM DUAL;  -- EM INGLES

SELECT TO_CHAR(SYSDATE, ' "PALMARES", FMDAY "," DD "DE" FMMONTH "DE" YYYY') FROM DUAL
SELECT TO_CHAR(SYSDATE, ' "PALMARES", DAY "," DD "DE" MONTH "DE" YYYY') FROM DUAL


-- FORMATAR EM HORA/MINUTOS
SELECT TO_CHAR(SYSDATE, 'HH24:MI') HORA_MIN FROM DUAL;

-- FORMATAR EM HORA/MINUTOS/SEGUNDOS
SELECT TO_CHAR(SYSDATE, 'HH24:MI:SS') HORA_MIN_SEG FROM DUAL;

-- FORMATAR EM DIA/MÊS/HORA/MINUTOS
SELECT TO_CHAR(SYSDATE, 'DD/MM HH24:MI') DATA_HORA FROM DUAL;

-- AULA 14

-- L -> R$
-- G -> PONTO
-- D -> CASAS DECIMAIS

SELECT TO_CHAR(SALARIO, 'L99999.99'), TO_CHAR(SALARIO, 'L99G999D99') FROM TALUNO;

SELECT TRIM(TO_CHAR(SALARIO, 'L99999.99')),
       TRIM(TO_CHAR(SALARIO, 'L99G999D99'))
FROM TALUNO;

SELECT 'R$'||(ROUND(SALARIO,2)) AS SALARIO FROM TALUNO;


-- NVL E NVL2
SELECT TOTAL,
       DESCONTO,
       DESCONTO+TOTAL,
       -- CASO A COLUNA SEJA NULA, ATRIBUI VALOR 0
       NVL(DESCONTO,0),
       NVL(DESCONTO,0) + TOTAL,
       -- NVL2 = 2 COLUNAS
       -- SE A COLUNA DESCONTO FOR NULA ATRIBUI -1,
       --   SENÃO ATRIBUI O VALOR DE TOTAL
       NVL2(DESCONTO, TOTAL, -1),
       -- SE A COLUNA DESCONTO FOR NULA, O VALOR ATRIBUÍDO VAI SER TOTAL,
       --   SENÃO ATRIBUI O VALOR -1
       NVL2(DESCONTO, -1, TOTAL),
       NVL2(DESCONTO, TOTAL, 0)
FROM TCONTRATO;


SELECT * FROM TALUNO

UPDATE TALUNO SET
NOME = NULL
WHERE COD_ALUNO = 5;

SELECT COD_ALUNO,
       NVL(NOME, 'SEM NOME')
FROM TALUNO


-- CASE || WHEN || THEN

UPDATE TALUNO SET
ESTADO = 'AC'
WHERE COD_ALUNO = 2;

UPDATE TALUNO SET
ESTADO = 'SC'
WHERE COD_ALUNO = 4;

UPDATE TALUNO SET
ESTADO = 'RJ'
WHERE COD_ALUNO = 5;

SELECT * FROM TALUNO

SELECT NOME, ESTADO,
       -- CASO
       CASE
        -- WHEN = QUANDO, THEN = ENTÃO
        WHEN ESTADO = 'RS' THEN 'GAUCHO'
        WHEN ESTADO = 'AC' THEN 'ACREANO'
        WHEN ESTADO = 'RJ' THEN 'CARIOCA'
        -- WHEN ESTADO = 'RJ' OR SALARIO > 500 THEN 'CARIOCA'
        -- WHEN ESTADO = 'RJ' AND SALARIO > 500 THEN 'CARIOCA'
        ELSE 'OUTROS'
       END AS APELIDO -- CASE ATÉ END = 1 COLUNA
FROM TALUNO;

-- DECODE
SELECT NOME, ESTADO,
       -- DECODIFICAR COLUNA -> EFEITO SEMELHANTE AO CASE
       --   SE 'RS', ENTÃO ATRIBUA 'GAUCHO'
       DECODE(ESTADO, 'RS', 'GAUCHO',
                      'AC', 'ACREANO',
                      'SP', 'PAULISTA',
                            'OUTROS') AS APELIDO -- SENÃO ATRIBUA 'OUTROS'
FROM TALUNO;



