SELECT [DISTINCT] {*, COLUMN [ALIAS], ...}
FROM NOME_TABLE;

/*
  NA SINTAXE:
  SELECT = É UMA LISTA DE UMA OU MAIS COLUNAS
  DISTINCT = SUPRIME DUPLICIDADES
  * = SELECIONA TODAS AS COLUNAS
  COLUMN = SELECIONA A COLUNA NOMEADA
  ALIAS = FORNECE TÍTULOS DIFERENTES PARA AS COLUNAS SELECIONADAS
  FROM NOME_TABLE = ESPECIFICA A TABELA QUE CONTÉM AS COLUNAS
*/


-- OPERAÇÕES COM COLUNAS COM VALORES NULL,
--  ANULAM A OPERAÇÃO INTEIRA


-- ALIAS
-- COM OU SEM AS
SELECT COD_ALUNO CODIGO, NOME AS ALUNO
FROM TALUNO;

-- COM ESPAÇO NO NOME
SELECT NOME "NOME DE ALUNO"
FROM TALUNO;


-- CONCATENAÇÃO
-- JUNTA AS COLUNAS E NOMEIA A MESMA
SELECT COD_ALUNO||NOME AS "ALUNO"
FROM TALUNO;

SELECT * FROM TALUNO


-- STRINGS DE CARACTERE LITERAIS: QUALQUER CARACTERE,
--  EXPRESSÃO OU NÚMERO EM ASPAS SIMPLES ''
SELECT NOME || ' NASCEU EM ' || CIDADE AS "NASCIMENTO DO ALUNO"
FROM TALUNO;


-- NA PRÁTICA:

-- ALIAS COM "" FORÇA AS LETRAS A FICAREM CAIXA BAIXA
SELECT COD_ALUNO AS "CODIGO", NOME AS "NOME DO ALUNO"
FROM TALUNO;


-- DISTINCT ANALISA A LINHA INTEIRA, NÃO APENAS "CÉLULAS"
SELECT DISTINCT CIDADE, COD_ALUNO
FROM TALUNO
-- ORDENA A COLUNA QUE IRÁ SER VISUALIZADA PRIMEIRO NA LISTAGEM
ORDER BY CIDADE;

SELECT * FROM TCURSO

ALTER TABLE TCURSO RENAME COLUMN CARGA_HORARIO TO CARGA_HORARIA;

SELECT NOME AS CURSO,
       VALOR,
       -- DIVISÃO P/ SABER VALOR DA HORA
       VALOR/CARGA_HORARIA,
       -- ARREDONDAR PARA DUAS CASAS DECIMAIS
       ROUND(VALOR/CARGA_HORARIA,2) AS VALOR_HORA
FROM TCURSO
-- ALIAS SÓ FUNCIONA EM ORDER BY
ORDER BY VALOR_HORA


SELECT * FROM TCONTRATO;

UPDATE TCONTRATO SET
DESCONTO = NULL
WHERE COD_CONTRATO = 4;

-- CÁLCULO COM COLUNA = NULL, RETORNA RESULTADO = NULL
SELECT COD_CONTRATO,
       TOTAL,
       DESCONTO,
       -- SOMA
       TOTAL+DESCONTO
FROM TCONTRATO;


SELECT COD_CONTRATO,
       DESCONTO,
       -- NVL: TRATA COLUNAS NULAS
       -- SE COLUNA FOR NULA, RETORNA IGUAL A 0
       NVL(DESCONTO,0),
       TOTAL,
       TOTAL + NVL(DESCONTO,0) AS TOTAL_MAIS_DESCONTO
FROM TCONTRATO;


-- CONCATENAÇÃO
SELECT COD_ALUNO || ' - ' || NOME || ' // ' || CIDADE AS ALUNO
FROM TALUNO
ORDER BY COD_ALUNO


-- TIPOS DE COLUNAS:
INTEGER = 1, 2 -- NÚMERO INTEIRO -> ATALHO PARA NUMBER(38)
NUMBER(5,2) = 999,99 -- NO MÁXIMO 3 DÍGITOS + 2 CASAS DECIMAIS
NUMBER(4,2) = 99,99 -- NUMBER = REPRESENTAR UMA QUANTIDADE OU VALOR
NUMERIC(5,2) = 999,99 -- NUMERIC = ADJETIVO QUE DESCREVE ALGO RELACIONADO A NÚMEROS OU VALORES NUMÉRICOS
DATE = '10/03/2011 00:00:00' -- SEMPRE APRESENTA A JUNÇÃO DE DATA E HORA NO RETORNO
VARCHAR -- SINÔNIMO DE VARCHAR2
VARCHAR2(10) = 'MARCIO' -- SE RESTRINGIR EM 10 CARACTERES E TER APENAS 6 EM USO, VAI OCUPAR ESPAÇO DE SOMENTE 6 NA MEMÓRIA
CHAR(10) = 'MARCIO    ' -- SE RESTRINGIR EM 10 CARACTERES E TER APENAS 6 EM USO, VAI OCUPAR ESPAÇO DE 10 NA MEMÓRIA

COMMIT;







